### ISSUE TITLE
to use "has_role_decorator" | queryset error

### ISSUE THREAD

**Issue by ferrada01** [vintasoftware/django-role-permissions#100]
Hello, when i use the nexts functions 
1) has_role_decorator
2) has_permission_decorator

**i recive the next error:** 
Traceback (most recent call last):
  File "/home/felipe/Escritorio/switch/enviroment/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/felipe/Escritorio/switch/enviroment/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/felipe/Escritorio/switch/enviroment/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/felipe/Escritorio/switch/flexMan/apps/views.py", line 178, in campanaView
    return vistaCampana(listas,request)
  File "/home/felipe/Escritorio/switch/enviroment/lib/python3.6/site-packages/rolepermissions/decorators.py", line 17, in wrapper
    user = request.user
AttributeError: 'QuerySet' object has no attribute 'user'

Thanks a lot!

**Comment by filipeximenes** [comment]
Hi @ferrada01. Could you send some code snippet with the code you are trying to run?

**Comment by ferrada01** [comment]
--------  in view.py  -------


@has_role_decorator('usuariokami')
def vistaCampana(listas,request):
	.
	.
	.

------ in my_app/role.py ------

class Usuariokami(AbstractUserRole):
    available_permissions = {
    	 #campana_permissions
        'crear_campana': True,
        'editar_campana':True,
        'borrar_campana':True,
        'ver_campana':True,
    }

----- in decorators.py ------

from __future__ import unicode_literals

from functools import wraps

from django.conf import settings
from django.contrib.auth.views import redirect_to_login as dj_redirect_to_login
from django.core.exceptions import PermissionDenied

from rolepermissions.checkers import has_role, has_permission
from rolepermissions.utils import user_is_authenticated


def has_role_decorator(role, redirect_to_login=None):
    def request_decorator(dispatch):
        @wraps(dispatch)
        def wrapper(request, *args, **kwargs):
            user = request.user  <-------- error line (I have entered the user manually, even so, I could not solve the error)
            if user_is_authenticated(user):
                if has_role(user, role):
                    return dispatch(request, *args, **kwargs)

            redirect = redirect_to_login
            if redirect is None:
                redirect = getattr(
                    settings, 'ROLEPERMISSIONS_REDIRECT_TO_LOGIN', False)
            if redirect:
                return dj_redirect_to_login(request.get_full_path())
            raise PermissionDenied
        return wrapper
    return request_decorator

**Comment by ferrada01** [comment]
I used the standard users  model that Django have

**Comment by ferrada01** [comment]
Solved, the problem was a double atribute passed to the view.

solution: pass only "request"
