### ISSUE TITLE
Object checkers can't be unit tested

### ISSUE THREAD

**Issue by finnertysea** [vintasoftware/django-role-permissions#102]
register_object_checker decorator returns None meaning the checkers can't be unit tested. I think this could be easily fixed by returning `func` from function_decorator.
```
def register_object_checker(name=None):
    def fuction_decorator(func):
        checker_name = name if name else func.__name__
        PermissionsManager.register_checker(checker_name, func)
        # return func
    return fuction_decorator
```
I'm happy to submit a pull request with a test case if this makes sense.

**Comment by filipeximenes** [comment]
Good point, yes please feel free to submit a PR. Thanks!

**Comment by fjsj** [comment]
Closed by https://github.com/vintasoftware/django-role-permissions/pull/103
