### ISSUE TITLE
Checker with name access_trial was not registered

### ISSUE THREAD

**Issue by hoffmka** [vintasoftware/django-role-permissions#104]
Hello, I'm trying to implement the object checker permissions function and have problems with registration. I added the file permissions.py to my app. (**myproject/apps/my_app/permissions.py**)
Here is the content of this file:

`from rolepermissions.permissions import register_object_checker
from predictDemo.roles import SystemAdmin

@register_object_checker()
def access_trial(role, user, trial):
    if user == trial.createdBy:
        return True
    return False`

If I check the permission with **has_object_permission('access_trial', user, trial)** than I get the error:
**Checker with name access_trial was not registered**

What am I doing wrong? Are there any requirements I haven't observed yet?
Thank you in advance for your efforts.
Katja

**Comment by filipeximenes** [comment]
Hi @hoffmka sorry for taking long to get back to you. Can you confirm that "my_app" is registered in the `INSTALLED_APPS` setting?

**Comment by hoffmka** [comment]
Thank you for your feedback! I can confirm that "apps.my_app" is registered in the INSTALLED_APPS setting. The app "my_app" is located in a subfolder "apps". But that doesn't seem to be the problem. I've tried this without a subdirectory.

**Comment by hoffmka** [comment]
Thank you, your comment has steered me in the right direction. I forgot to import the permissions. --> **from apps.myapps import permissions**
It works now!

**Comment by filipeximenes** [comment]
Awesome! Closing the ticket!
