### ISSUE TITLE
Is there a way to filter the users of a particular role from the model?

### ISSUE THREAD

**Issue by mezitax** [vintasoftware/django-role-permissions#106]
I explain:
In my model I have something like this:
`teacher = models.ForeignKey (settings.AUTH_USER_MODEL)`
I wish the ForeignKey could select only users with the role of "teacher"

**Comment by filipeximenes** [comment]
If I understand the question correctly, you are looking for something like this:
```User.objects.filter(groups__name="teacher")```

Would this solve your problem?

**Comment by mezitax** [comment]
thank you, I forgot to close this issue
That's what I was referring to, but at the model level.
Finally, for practical purposes, I created a proxy user model for users who belong to the teacher group
