### ISSUE TITLE
permissions with default false are never created

### ISSUE THREAD

**Issue by iurisilvio** [vintasoftware/django-role-permissions#112]
Is it expected behaviour? How can I create these permissions to be able to give permissions manually on admin?

https://github.com/vintasoftware/django-role-permissions/blob/master/rolepermissions/roles.py#L149-L157

**Comment by filipeximenes** [comment]
@iurisilvio yes, this is expected. They are only created in the first time they are needed. You can use `grant_permission` to do it in the first time and then it should be available in the admin

**Comment by iurisilvio** [comment]
The problem with this behaviour is I need a manual step before I use the permission in admin.

Do you consider a flag to sync these false values too? Something like `sync_roles --all-permissions`?

I can work on that if it makes sense for the project.

I'll do it for my project anyway.

**Comment by filipeximenes** [comment]
Yes, that sounds like a good idea!

**Comment by iurisilvio** [comment]
I opened a pull request with these changes.
