### ISSUE TITLE
Create Dynamically  roles  

### ISSUE THREAD

**Issue by Izcarmt95** [vintasoftware/django-role-permissions#115]
Hi,  I have a question.

I have been using this library with roles classes, but  I have a problem that I want to create  roles through  user interfaces, and this interfaces has some fields like:
- name role
-  Select list with permissions.

My question is, Can I create roles and saving in DB and use them with a generic class  ?

**Comment by joshuakoh7** [comment]
I'm interested in this as well. My understanding is that if you have a dynamic list you would have to do a reload after every update?

**Comment by Izcarmt95** [comment]
Yeah , I want to create roles throught interfaces but in this moment the role are just creating hardcoded with classes and every time I want to create roles I am needing write the rol class and after reload that update

**Comment by filipeximenes** [comment]
Hi folks, dynamic roles is not something that is [officially] supported in the lib. If you managed to get this going please let me know and I can check if this is something we'd like to support in future versions. For now I'm closing this issue, feel free to reopen it in case you want to discuss this further.
Stay safe!
