### ISSUE TITLE
Can I do this with this git project? 

### ISSUE THREAD

**Issue by simeon49** [vintasoftware/django-role-permissions#127]
Hello everyone, we have the following requirements recently.

in departmet/models.py 
```python
class Department(models.Model):
      name = models.CharField()
      ....
```

in customer_resources/models.py
```python
class CustomerResource(models.Model):
      customer = models.ForeignKey(User)
      belong_department = models.ForeignKey(Department)

     class Meta:
        default_permissions = ()
        permissions = [
            ('view_customer_resource', 'can view customer info'),
            ('change_customer_resource', 'can change customer info'),
            ....
        ]
```

I want create a manager group for department A, the one who is in this group can "view", "change", ... all the customer resources that belong to department A.

```python
depart_a = Department(...)
depart_a_manager_group = Group.objects.create(...)

assign_perm('view_customer_resource', depart_a_manager_group, depart_a)

manager_01 = User(...)
manager_01.groups.add(depart_a_manager_group)

customer_01 = CustomerResource(belong_department=depart_a, ...)
assert user.has_permissions('view_customer_resource', customer_01), 'how to do this???, any one help'
```
Can I do this with this git project?

**Comment by simeon49** [comment]
any one help?

**Comment by filipeximenes** [comment]
Hi @simeon49, yes, I believe this project is capable of doing something like what you described. But that's pretty what most permission libraries you find [including the default django permissions tooling] will do, so I suggest you study the docs and play with the library before you decide if it fits your needs

**Comment by simeon49** [comment]
> Hi @simeon49, yes, I believe this project is capable of doing something like what you described. But that's pretty what most permission libraries you find [including the default django permissions tooling] will do, so I suggest you study the docs and play with the library before you decide if it fits your needs

Thank you

**Comment by filipeximenes** [comment]
I'm going to close this ticket for now, feel free to reopen it in case you have more questions :)
