### ISSUE TITLE
Can role classes be created dynamically?

### ISSUE THREAD

**Issue by anmolbk** [vintasoftware/django-role-permissions#128]
To enable users to create arbitrary roles as they require, I think the role classes need to be created dynamically. Will adding the dynamically created role classes to "roles" module work? I guess not, as the role classes seem to be loaded on startup. Any possibility to reload roles (& permissions) every time a new role class (or permission) is created?

**Comment by filipeximenes** [comment]
The lib was not designed to work with dynamic roles. You can probably hack some solution but there's a risk you have compatibility problems so I wouldn't recommend
