### ISSUE TITLE
Giving user a role from the admin pages doesn't update permissions?

### ISSUE THREAD

**Issue by AliD201** [vintasoftware/django-role-permissions#130]
Hope you are doing well. 

when registering a new user in this part 

        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save() # store the user 
            username = form.cleaned_data.get('username')
            messages.success(request,f'  {username}  account created succefully')
            return redirect('login')
            
and then adding a group to that user through the admin page. the user permissions doesn't  change, Why is that ? 
i need to run `sync_role` for each user from the shell in order for it to sync

**Comment by filipeximenes** [comment]
Hi @AliD201, did you read through this section of the docs? https://django-role-permissions.readthedocs.io/en/stable/admin.html#rolepermissions-user-admin

**Comment by vaishnavi-2901** [comment]
For that, you need to enable 

[ROLEPERMISSIONS_REGISTER_ADMIN](https://django-role-permissions.readthedocs.io/en/stable/settings.html#register-user-admin-setting) = True

**Comment by fjsj** [comment]
Thanks, I imagine this is solved then. Closing.
