### ISSUE TITLE
Error installing with pip

### ISSUE THREAD

**Issue by johngamarra** [vintasoftware/django-role-permissions#17]
Hi,

I'm getting this error when trying to install this package with pip:

C:\Python34>cd scripts

C:\Python34\Scripts>pip install django-role-permissions
Downloading/unpacking django-role-permissions
  Downloading django-role-permissions-0.4.2.tar.gz
  Running setup.py (path:C:\Users\Manuel\AppData\Local\Temp\pip_build_Manuel\dja
ngo-role-permissions\setup.py) egg_info for package django-role-permissions
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "C:\Users\Manuel\AppData\Local\Temp\pip_build_Manuel\django-role-perm
issions\setup.py", line 59
        print "You probably want to also tag the version now:"
                                                             ^
    SyntaxError: Missing parentheses in call to 'print'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "C:\Users\Manuel\AppData\Local\Temp\pip_build_Manuel\django-role-permissi
ons\setup.py", line 59

    print "You probably want to also tag the version now:"

                                                         ^

SyntaxError: Missing parentheses in call to 'print'

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in C:\Users\Manuel\App
Data\Local\Temp\pip_build_Manuel\django-role-permissions
Storing debug log for failure in C:\Users\Manuel\pip\pip.log

Why can this be happening? maybe I need something else? sorry if it's my fault  I'm new to python

**Comment by luzfcb** [comment]
@johngamarra this is a bug.

this is happening because setup.py use Python2 only print function, and in Python3 is now mandatory use `( )` on `print` function 

Python2 only:
`print "You probably want to also tag the version now:"`

Python 2 and Python3 compatible

`print("You probably want to also tag the version now:")`

I have not tested, you can download https://github.com/vintasoftware/django-role-permissions/archive/master.zip , unzip and change the setup.py file

from:
```python
    print "You probably want to also tag the version now:"
    print "  git tag -a %(version)s -m 'version %(version)s'" % args
    print "  git push --tags"
```

to:
```python
    print("You probably want to also tag the version now:")
    print("  git tag -a %(version)s -m 'version %(version)s'" % args)
    print("  git push --tags")
```

after, run `python setup.py install`

**Comment by luzfcb** [comment]
@johngamarra 
you can learn more about this by reading:

https://docs.python.org/3/howto/pyporting.html
http://python3porting.com/foreword.html

**Comment by filipeximenes** [comment]
Thanks @luzfcb!
This django-role-permissions is not currently python3 compatible, but I do wish it was. It would be great if someone could help me with this.

**Comment by balavec** [comment]
Is it only because of the print function or is there something else ...
@luzfcb is there an alternative for Python3 ?

**Comment by filipeximenes** [comment]
This is now Python 3 compatible. =)

@balavec
@luzfcb 
@johngamarra

**Comment by luzfcb** [comment]
:tada: :dancers: :tada:
