### ISSUE TITLE
Django 1.9 warning

### ISSUE THREAD

**Issue by DeoLeung** [vintasoftware/django-role-permissions#24]
Receiving following warnings, shall update the import, not urgent anyway.

/usr/local/lib/python2.7/dist-packages/rolepermissions/loader.py:4: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  from django.utils.importlib import import_module

https://docs.djangoproject.com/en/1.8/releases/1.7/#django-utils-dictconfig-django-utils-importlib

**Comment by filipeximenes** [comment]
Yes, Django 1.9 is on it's way, we should fix this. 
Thanks for creating the issue.  
A PR with a fix would also be much appreciated since i'm bit short on time.

**Comment by filipeximenes** [comment]
On pypi as version 0.6.2
