### ISSUE TITLE
available_perm_status: 'UserPermission' is not defined

### ISSUE THREAD

**Issue by jassi5887** [vintasoftware/django-role-permissions#25]
Hi, 
I am trying to use it with Django1.8 but I keep getting **'UserPermission' is not defined**. Following is what I did and yes I have included it in settings.py and migrated:

    from college.roles import Student
    student = User.objects.get(username='jassi')
    Student.assign_role_to_user(student)
    from rolepermissions.shortcuts import available_perm_status
    permis = available_perm_status(student)

error

    Traceback (most recent call last):
     File "<console>", line 1, in <module>
     File "/home/jassi/.venvs/college/local/lib/python2.7/site-packages/rolepermissions/shortcuts.py",   line 33, in available_perm_status
    permissions = UserPermission.objects.filter(user=user)
    NameError: global name 'UserPermission' is not defined

**Comment by filipeximenes** [comment]
Awkward. This method has code from a very old version of role-permissions and for some reason was not tested. 
Working on it now.

**Comment by filipeximenes** [comment]
Fixed. Update from pypi to version 0.6.1 and it should work.

**Comment by jassi5887** [comment]
it works now, thanks !
