### ISSUE TITLE
Django 1.9 support

### ISSUE THREAD

**Issue by filipeximenes** [vintasoftware/django-role-permissions#34]

**Comment by filipeximenes** [comment]
Working on branch django19

**Comment by AdrianRibao** [comment]
Hi,

is this ready to be merged?

Thanks!

**Comment by filipeximenes** [comment]
It's not merged yet because I didn't have a chance to test in a real project yet. I think I can do it by next week, but if you are available, could you give it a try and let me know it works correctly?

**Comment by filipeximenes** [comment]
Merged
