### ISSUE TITLE
Support multiple roles

### ISSUE THREAD

**Issue by cormier** [vintasoftware/django-role-permissions#38]
From what I've seen in the code, it seems that though the app could support multiple roles per user, it supports only one.

For example `assign_role_to_user` will delete all of the user's previous roles:
https://github.com/vintasoftware/django-role-permissions/blob/master/rolepermissions/roles.py#L50

And `get_user_role` explicitely return only the first role if the user has multiple roles:
https://github.com/vintasoftware/django-role-permissions/blob/74ad8cc3d3983e9661658b28e217b2bbab086373/rolepermissions/shortcuts.py#L21

Is there a reason for not supporting multiple roles? Before diving into the code, I would like to have an idea on how difficult could implementing such a feature be ? Would a PR working towards implementing this feature be considered?

Thanks.

**Comment by filipeximenes** [comment]
Yes, the app was though for a role per user. In most scenarios this works well and you can manage more specific stuff using permissions. 
When you assign a role to a user you can still change it's permissions, so it's a very flexible approach.

Could you tell me more about your use case?

You are welcome to propose a new interface to allow a user having multiple roles. Please send some examples on how you think we should do it. Keep in mind we have to keep the current interface working so other apps don't break. But if your approach is much better than the current one, we may even make breaking changes and release it as version 2.0.

**Comment by lucaswelper** [comment]
I'm not currently using django-role-permissions, but have it in mind for a couple projects I'd like to replace at work and was initially put off by the lack support for multiple roles.

All of our current systems allow multiple roles be assigned to a single user.  We have situations such as:
> 1. "Reviewer" role has edit access to all objects of model A, but only in certain states
> 2. "Read Only" role has view access to all objects of model A, in all states
> 3. Some reviewers are granted the read-only role as well.

It would be possible to create a third role, reviewer_with_readonly, but I think this approach would result in a lot of duplication (permissions within roles, role checking in views, etc)

**Comment by ChristofferKarlsson** [comment]
If you have a site with multiple apps where different users have different roles in each app, it would be very convenient to be able to assign roles. One such use case could be a site with the following apps and their respective roles (pretty close to a project I run):
News: news_publisher, news_reviewer
Articles: article_publisher, article_reviewer
Forum: forum_admin, forum_moderator
Mail-list: maillist_admin, maillist_publisher

If users are allowed to have different roles in different apps, then it would be much duplication to cover each possible set of roles.

**Comment by CarlosBorroto** [comment]
+1 for multiple roles support.

Not my use case but I think a good example in support of multiple rules. In a school environment I can see a user playing several of these roles.

Roles:
Principal, Teacher, Teacher Assistant, Admin Staff, Staff, Student

**Comment by giocalitri** [comment]
+1 also from me.
My use case is that I have multiple roles with not overlapping permissions ("forum admin", "chat admin", "site staff", etc.) and I want to assign many roles to the same user and not create superset of permissions.

I might be able update the code by myself, but I would like some hints about what I should take in account.
My idea was to modify `assign_role_to_user` in a way that I can preserve the previous assigned roles

```
@classmethod
    def assign_role_to_user(cls, user, remove_previos_roles=True):
        """
        Deletes all of user's previous roles, and removes all permissions
        mentioned in their available_permissions property.
        :returns: :py:class:`django.contrib.auth.models.Group` The group for the
            new role.
        """
        if remove_previos_roles:
            from rolepermissions.shortcuts import remove_role
            remove_role(user)
```
is this enough or should i take in account something else I am missing?

**Comment by filipeximenes** [comment]
@giocalitri it should take a little more than that. Many functions assume a single role, we will need to change the way we check for roles and permissions.

**Comment by giocalitri** [comment]
@filipeximenes I understand. I might still be able make the work if I have a clear list of what I need to modify.

Sorry for putting pressure, but I have a strict deadline and if this does not work for you I need to move on and find another solution.

**Comment by filipeximenes** [comment]
@giocalitri You will need to check on all functions in these files:

https://github.com/vintasoftware/django-role-permissions/blob/master/rolepermissions/verifications.py

https://github.com/vintasoftware/django-role-permissions/blob/master/rolepermissions/shortcuts.py

Some notes:
- `remove_role` will need to receive the name of the role
- We will need a function to remove ALL roles at once
- Be careful on `grant_permission` and `revoke_permission` as they will need to check if the permission is available in any of the roles
- Make sure you keep all the existing tests and add new ones for every function considering the possibility of multiple roles
- We will need to update all the docs
- This will be released as version 2.0

**Comment by giocalitri** [comment]
@filipeximenes Thanks for the input. 
I will start to work on this from, likely, tomorrow. 
I plan to have a PR by the end of next week.

When do you plan to release 2.0?

**Comment by filipeximenes** [comment]
@giocalitri As soon as we meet all the requirements for a stable release (a.k.a. do everything in the notes above :P)

**Comment by giocalitri** [comment]
@filipeximenes Great! 
I am sure I will have some other questions: is this issue a good way to discuss?

**Comment by filipeximenes** [comment]
Yes, this way everyone can participate.

**Comment by bartonaz** [comment]
@filipeximenes Was there any progress on this? According to the docs, there is still no support of multiple roles per user.

**Comment by filipeximenes** [comment]
@bartonaz I haven't head from @giocalitri so far

**Comment by kavdev** [comment]
@filipeximenes @bartonaz @giocalitri: Luckily my work needs this, so if nothing comes up, I should be able to get a PR in by the end of the week.

**Comment by g20ready** [comment]
@kavdev I have also implemented a similar functionality. you might want to take a look [here](https://github.com/g20ready/django-role-permissions). I still haven't finished with testing and the specs i want to use but still its functional.

**Comment by filipeximenes** [comment]
This is up on PyPI as version 2.0.0.
Thanks very much for everyone's contributions, and @kavdev for the PR.
