### ISSUE TITLE
HasRoleMixin could redirect to login page

### ISSUE THREAD

**Issue by huogerac** [vintasoftware/django-role-permissions#39]
I've just started using the django-role-permissions and loved it.

I'd like to block my Views (CBV) for specific Roles:

```
class MyListView(HasRoleMixin, ListView):
        allowed_roles = 'Admin'
        ...
```

It's working in terms of permissions, however, I'd like to be redirect to the login page when I have no permission or not logged in rather than get a 403 Forbidden error.

My solution today is using role-permissions + django-braces where I do something like bellow rather than the HasRoleMixin:

```
class MyListView(LoginRequiredMixin, UserPassesTestMixin, ListView):

    def test_func(self, user):
        return has_role(user, [Admin, ])
```

This way, when the user has no permission, it goes to the login page and the workflow works very well.

Is there any settings that I could do this behavior without using braces? in other others, intercept the 403 error and do something else?

I'd be happy if you guys give me some directions that lead me to do some pull request and contribute to this amazing app.

Cheers

**Comment by filipeximenes** [comment]
Hi @huogerac, sorry for taking so long to answer, was little short on time. 
Thanks for reporting this, what you can do is create another mixin, that extends `HasRoleMixin` and `try/excepts` looking for `PermissionDenied` exception, if it's raised you would redirect to login view. 
A PR with this would certainly be very welcome.

**Comment by huogerac** [comment]
Hey Filipe, I'll try to do what you've recommended. I hope to push a PR soon.
Cheers

**Comment by huogerac** [comment]
Hi @filipeximenes, I've tried a different approach than extending the `HasRoleMixin`, please let me know if you don't like it.
I tested in my current project and it worked very well, I couldn't run the internal tests (see the Issue #40)

Cheers and I hope this make sense...
