### ISSUE TITLE
Checker always returns True result

### ISSUE THREAD

**Issue by ishrivatsa** [vintasoftware/django-role-permissions#69]
Hi, The checkers method is returning permission result as available, when we assign a role and remove it.

**Comment by filipeximenes** [comment]
Hi @ishrivatsa, can you provide more context? What version of the lib are you using? Can you provide a sample of the code you are seeing this behavior (please provide the role class)? Which checker method are you using?

**Comment by ishrivatsa** [comment]
>>> from rolepermissions.roles import assign_role
>>> from django.db.auth.models import User
>>> user = User.objects.get(id=1)
>>> assign_role(user, 'doctor')
<class 'tml.roles.Doctor'>
>>> from rolepermissions.checkers import has_permission
>>> has_permission(user, 'create_medical_record')
True
>>> has_permission(user, 'edit_patient_file')
True


The second time I run the has_permission, it should have returned false. 

I am running python 3.5 in a virtual env. Django 1.10.2

Thank you.

**Comment by filipeximenes** [comment]
Thanks! I need more information: 
- What django-role-permissions version are you using?
- Can you paste the code for the `Doctor` role (or some version of it)?
- Does this user have any other roles assigned?
- Is this happening with fresh created users?

**Comment by ishrivatsa** [comment]
Hi, 
-  I am using version 2.0.1
- Its the exact same code on the tutorial page. 

from rolepermissions.roles import AbstractUserRole

class Doctor(AbstractUserRole):
    available_permissions = {
        'create_medical_record': True,
    }

class Nurse(AbstractUserRole):
    available_permissions = {
        'edit_patient_file': True,
    }

- Its happening both with freshly created users and existing users. 

Thank you.

**Comment by ishrivatsa** [comment]
Hi @filipeximenes , 
 I downloaded the source code from github and imported it into the project. That seems to be working !!

**Comment by vinyasmusic** [comment]
@ishrivatsa I am facing the same issue. How to solve this ?

**Comment by vinyasmusic** [comment]
Looked at the code, it always returns true if the user is an superuser/admin
Clarified

**Comment by filipeximenes** [comment]
@vinyasmusic yes, that's right. It's actually a discussion we are having. Here is the link if you want to contribute: https://github.com/vintasoftware/django-role-permissions/issues/61#issuecomment-306895464
