### ISSUE TITLE
Not supported for rest framework ( django rest api )

### ISSUE THREAD

**Issue by cmaliwal** [vintasoftware/django-role-permissions#73]
This library not supported for django RESTAPI .

**Comment by fjsj** [comment]
@cmaliwal please provide a full example. Have you tried using the mixins? http://django-role-permissions.readthedocs.io/en/stable/views_utils.html#mixins

**Comment by cmaliwal** [comment]
@fjsj I haven't tried mixins in my DRF views.
I am trying to using has_role decorator before my views ( note : i am using Function based Views not class based views ).

I will provide you full code for better understanding.

**Comment by cmaliwal** [comment]
I am getting error on has_role detectors on line number 17.

user = request.user
Decorator not getting request.user.

**Comment by filipeximenes** [comment]
@cmaliwal I guess this was solved right? Please reopen if needed.
