### ISSUE TITLE
model User is not registered

### ISSUE THREAD

**Issue by philippeluickx** [vintasoftware/django-role-permissions#76]
```
  File "/home/x/y/.venvs/z/lib/python3.6/site-packages/rolepermissions/admin.py", line 40, in <module>
    admin.site.unregister(UserModel)
  File "/home/x/y/.venvs/z/lib/python3.6/site-packages/django/contrib/admin/sites.py", line 136, in unregister
    raise NotRegistered('The model %s is not registered' % model.__name__)
django.contrib.admin.sites.NotRegistered: The model User is not registered
```

I have 2 roles defined and one superuser that has neither defined (fresh deployment of site), but for which I want to define a role through admin interface.

edit: I am using a custom user model.

**Comment by filipeximenes** [comment]
@philippeluickx you are using `ROLEPERMISSIONS_REGISTER_ADMIN = True`, right?
For custom user models use the `RolePermissionsUserAdminMixin` (check here http://django-role-permissions.readthedocs.io/en/stable/admin.html?highlight=RolePermissionsUserAdminMixin#RolePermissionsUserAdminMixin)

I guess we should improve the docs for this. I'll leave the issue open util we fix it.

**Comment by philippeluickx** [comment]
That's indeed what I ended up doing, +1 on improving the docs.
Also, thanks for the admin integration, that really helps a lot!

**Comment by filipeximenes** [comment]
That's all on @powderflask! They did a great job on this!

**Comment by philippeluickx** [comment]
https://github.com/vintasoftware/django-role-permissions/pull/78

**Comment by filipeximenes** [comment]
Awesome! Thank you!

**Comment by larspeyer** [comment]
Small add on to the solution of @filipeximenes:
You have to remove the setting `ROLEPERMISSIONS_REGISTER_ADMIN = True` from `settings.py`
