### ISSUE TITLE
Cant access get the functions to return roles in my views or template

### ISSUE THREAD

**Issue by aldo123** [vintasoftware/django-role-permissions#79]
Hi, Great Package, I have a small issue or I am missing something, in any I need help, now I can assign roles, but I can only successfully return when I am using the shell, it completely fails on when trying vies or templates. 

Its probably a very easy problem to solve

thanks in  advance.
A

**Comment by filipeximenes** [comment]
Hey, can you provide some more information? What is the code you are running?

**Comment by aldo123** [comment]
Thank you for your response, but I fixed the problem

**Comment by filipeximenes** [comment]
Cool :)
