### ISSUE TITLE
Changelog for 2.2.0

### ISSUE THREAD

**Issue by JoelGoh92** [vintasoftware/django-role-permissions#80]
Hi,

I would like to ask if there is any changelog detailing the changes made between versions released, especially between 2.2.0 and 2.1.0? 
Thanks

**Comment by JoelGoh92** [comment]
@filipeximenes Thanks for the quick response. 

The reason why I'm asking for this changelog is because the recent update from 2.1.0 to 2.2.0 broke something on my project's end, when we tried to update this package, which might be related to [issue #76](https://github.com/vintasoftware/django-role-permissions/issues/76) raised previously. 

Anyways, will you guys be planning to release a detailed changelog for future version release changes? 

This would greatly help all third party users using this project to understand the breaking/non-breaking features between version releases to make the necessary changes.

**Comment by filipeximenes** [comment]
@JoelGoh92 very sorry for the delay, busy weeks. Yes, let's add changelog to the release process. So you still have have a problem? Is there anything left to be fixed?

**Comment by JoelGoh92** [comment]
@filipeximenes Thanks for the response. I've also managed to get around the issue by using the RolePermissionsUserAdminMixin as described in [issue #76](https://github.com/vintasoftware/django-role-permissions/issues/76). Looking forward to the changelog!
