### ISSUE TITLE
Remove CI build for py34-djangolatest

### ISSUE THREAD

**Issue by lucabezerra** [vintasoftware/django-role-permissions#84]
`djangolatest` is currently >= 2.0, Python 3.4 doesn't seem to be supported by it, according to the CI's errors: https://travis-ci.org/vintasoftware/django-role-permissions/jobs/360877392

**Comment by lucabezerra** [comment]
@chocoelho Did I get this right or is the error related to a dependency instead of Django?

**Comment by chocoelho** [comment]
That's correct. Django 2 dropped support for any Python version lesser than 3.5.

**Comment by filipeximenes** [comment]
Done!
