### ISSUE TITLE
The role didn't have permission in database

### ISSUE THREAD

**Issue by rensg001** [vintasoftware/django-role-permissions#86]
I use django 1.9.6
The role created in roles module didn't include permissions in database.

if i have defined Doctor role in roles module and it include create_medical_record permission, then i use sync_roles command, but the group's permission attribute didn't include that permission.

could you fix it?

in addition, could you add a place to define permission name in role class??if some people use another language maybe useful.

**Comment by filipeximenes** [comment]
DRP does not handles permissions at Group level
