### ISSUE TITLE
Error creating new user

### ISSUE THREAD

**Issue by PedroMendes96** [vintasoftware/django-role-permissions#88]
Hello, i was trying to integrate this package in my project but i got an error when i try to create a new user. 

File "C:\Users\PEDROM~1\Envs\dcs\lib\site-packages\django\contrib\auth\base_user.py", line 80, in save
    super(AbstractBaseUser, self).save(*args, **kwargs)
  File "C:\Users\PEDROM~1\Envs\dcs\lib\site-packages\django\db\models\base.py", line 808, in save
    force_update=force_update, update_fields=update_fields)
  File "C:\Users\PEDROM~1\Envs\dcs\lib\site-packages\django\db\models\base.py", line 848, in save_base
    update_fields=update_fields, raw=raw, using=using,
  File "C:\Users\PEDROM~1\Envs\dcs\lib\site-packages\django\dispatch\dispatcher.py", line 193, in send
    for receiver in self._live_receivers(sender)
  File "C:\Users\PEDROM~1\Envs\dcs\lib\site-packages\django\dispatch\dispatcher.py", line 193, in <listcomp>
    for receiver in self._live_receivers(sender)
  File "C:\Users\Pedro Mendes\Documents\teste\app_dcs\source\dcas\signals.py", line 106, in give_minimum_roles
    assign_role(sender, 'pedidos')
  File "C:\Users\PEDROM~1\Envs\dcs\lib\site-packages\rolepermissions\roles.py", line 226, in assign_role
    return _assign_or_remove_role(user, role, "assign_role_to_user")
  File "C:\Users\PEDROM~1\Envs\dcs\lib\site-packages\rolepermissions\roles.py", line 219, in _assign_or_remove_role
    getattr(role_cls, method_name)(user)
  File "C:\Users\PEDROM~1\Envs\dcs\lib\site-packages\rolepermissions\roles.py", line 67, in assign_role_to_user
    permissions_to_add = cls.get_default_true_permissions()
AttributeError: 'ManyToManyDescriptor' object has no attribute 'add'

to be more precise:

@add_metaclass(RolesClassRegister)
class AbstractUserRole(object):

    <...>

    @classmethod
    def assign_role_to_user(cls, user):
        """
        Assign this role to a user.

        :returns: :py:class:`django.contrib.auth.models.Group` The group for the
            new role.
        """
        group, _created = Group.objects.get_or_create(name=cls.get_name())
        user.groups.add(group) 
        permissions_to_add = cls.get_default_true_permissions()
        user.user_permissions.add(*permissions_to_add)

the line of code "user.groups.add(group) " make that error. I create my own User model but i dont think that is a problem because it inherits AbstractUser.

**Comment by filipeximenes** [comment]
Hi @PedroMendes96, could you provde the code your are running (in your code base) that provoked that error?

**Comment by PedroMendes96** [comment]
Hi @filipeximenes , thanks for replying:

Here is the code base:
class Command(BaseCommand):
# command to guarantee the existence of an admnistrator 

    def add_arguments(self, parser):
        parser.add_argument('username', nargs='+', type=str,default=None)
        parser.add_argument('email', nargs='+', type=str,default=None)
        parser.add_argument('password', nargs='+', type=str,default=None)

    def handle(self, *args, **options):
        try:
            email = options['email'][0]
        except Exception as identifier:
            email = settings.SUPER_USER_EMAIL
        
        try:
            username = options['username'][0]
        except Exception as identifier:
            username = settings.SUPER_USER_USERNAME
        
        try:
            password = options['password'][0]
        except Exception as identifier:
            password = settings.SUPER_USER_PASSWORD

        if email and username and password:
            try:
                user = User.objects.create(is_superuser=True,username=username,email=email,is_staff=True,is_active=True,date_joined=timezone.localtime())
                user.set_password(password)
                user.save()
                print("SUCESS: THE SUPER USER WAS CREATED.")
                token = Token.objects.create(user=user)
                token.save()
                return token.key
            except Exception as identifier:
                print("ERROR: THE USER WITH THAT EMAIL OR USERNAME ALREADY EXISTS.")
                user = User.objects.get(email=email)
                user.set_password("somepassword")
                user.save()
                tokens = Token.objects.filter(user=user)
                if len(tokens) > 0:
                    return tokens[0].key
                else:
                    token = Token.objects.create(user=user)
                    token.save()
                    return token.key

This error occur two times in this code, 1º when i call user.objects.create 2º and after that in the except clause when it runs user.save()

**Comment by filipeximenes** [comment]
Thanks! I don't see exactly where you are calling a function from `django-role-permissions`. Perhaps it is in your custom user `save` method?

**Comment by PedroMendes96** [comment]
Sorry i forgot.

When i create a user i wanted to give him some permissions, so i created a signal:

@receiver(post_save,sender=settings.AUTH_USER_MODEL)
def give_minimum_roles(sender, instance, **kwargs):
    if sender.is_staff:
        assign_role(sender, 'pedidos')
        assign_role(sender, 'assinaturas')

If i comment this block of code it works fine.

**Comment by filipeximenes** [comment]
Aha! So, you are doing the operation in the `sender` which is the `User` *model* not an *user model instance*. Replace `sender` with `instance` in the body of that function and it should work

**Comment by PedroMendes96** [comment]
Oh... im so sorry i actually did see that mistake! Thank you for the help!
