### ISSUE TITLE
Single user with different roles in multiple projects

### ISSUE THREAD

**Issue by tcosta84** [vintasoftware/django-role-permissions#91]
I'm working on a project manager tool right now where a single user is a member of multiple projects and in each one he can have a different role.

I'm starting with a standard User object from Django, a Project object and planning to have a junction object between User and Project.

Is it possible to have a role for this junction object?

Thanks!

**Comment by filipeximenes** [comment]
Hey, sorry for the delay, busy week. Hmm, I don't think this will work. Django Role Permissions works directly with the user model swapping that wouldn't be easy.

**Comment by ajeebkp23** [comment]
> I'm working on a project manager tool right now where a single user is a member of multiple projects and in each one he can have a different role.
> 
> I'm starting with a standard User object from Django, a Project object and planning to have a junction object between User and Project.
> 
> Is it possible to have a role for this junction object?
> 
> Thanks!

I think, you have to use object permissions. [https://django-role-permissions.readthedocs.io/en/stable/object_permissions.html](https://django-role-permissions.readthedocs.io/en/stable/object_permissions.html)

**Comment by filipeximenes** [comment]
@ajeebkp23 yes, this would possible work with object permissions, but the Role functionality wouldn't work. I'm closing this for now
