### ISSUE TITLE
I do not see selected permissions on admin page

### ISSUE THREAD

**Issue by mezitax** [vintasoftware/django-role-permissions#94]
I've been testing the integration with the admin, I created an "administrator" role with some permissions, run "django-admin sync_roles", but the permission comes out in the list of available permissions and not within the selected group
```
from rolepermissions.roles import AbstractUserRole

class Administrador(AbstractUserRole):
    available_permissions = {
        'can_add_rainbow': True,
    }
```

![image](https://user-images.githubusercontent.com/1774655/49620121-5d48c800-f99e-11e8-93f8-f22b7b20a249.png)

I'm missing something?

**Comment by filipeximenes** [comment]
Hey @mezitax, it should show up after the first time you assign this role to a user. Please LMK if this works for you.

**Comment by mezitax** [comment]
ok, it works!
Now I understand how django-role adds the permissions to the end user and not to the group. it works perfect for me
Thank you

**Comment by filipeximenes** [comment]
Cool! Closing this!
